"""
Base declarative class, UUIDv7 generator, and shared column helpers.

Standards (from db-schema.md):
- All IDs are UUIDv7, generated by application code (not database default).
- All user-visible timestamps are timestamptz in UTC.
- All business tables include center_id.
"""

from __future__ import annotations

import time
import uuid
from datetime import UTC, datetime
from typing import Annotated, Any

from sqlalchemy import DateTime, text
from sqlalchemy.orm import DeclarativeBase, MappedColumn, mapped_column


# ── UUIDv7 generator ──────────────────────────────────────────────────────────

def generate_uuid7() -> uuid.UUID:
    """
    Generate a UUIDv7 (time-ordered UUID per draft-ietf-uuidrev-rfc4122bis).

    Layout:
      - 48 bits: Unix timestamp in milliseconds
      -  4 bits: version (0b0111)
      - 12 bits: sub-millisecond precision / random sequence
      -  2 bits: variant (0b10)
      - 62 bits: random

    Application-generated; never delegated to the database.
    """
    ts_ms = int(time.time() * 1000)
    rand = uuid.uuid4().int & ((1 << 74) - 1)  # 74 random bits

    uuid_int = (
        (ts_ms & 0xFFFFFFFFFFFF) << 80          # 48-bit timestamp
        | (0x7 << 76)                            # 4-bit version = 7
        | ((rand >> 62) & 0xFFF) << 64          # 12-bit seq/rand
        | (0b10 << 62)                           # 2-bit variant
        | (rand & ((1 << 62) - 1))              # 62-bit random
    )
    return uuid.UUID(int=uuid_int)


# ── Shared column type aliases ─────────────────────────────────────────────────

# timestamptz column — always UTC, timezone-aware
def utc_now() -> datetime:
    return datetime.now(UTC)


TimestampTZ = Annotated[
    datetime,
    MappedColumn(DateTime(timezone=True), nullable=False),
]

OptionalTimestampTZ = Annotated[
    datetime | None,
    MappedColumn(DateTime(timezone=True), nullable=True),
]


# ── Declarative base ───────────────────────────────────────────────────────────

class Base(DeclarativeBase):
    """
    Shared SQLAlchemy declarative base.

    All ORM models inherit from this. The metadata object is the single
    source of truth used by Alembic autogenerate.
    """

    type_annotation_map: dict[Any, Any] = {}
