"""initial_schema

Revision ID: ddf7328e83fa
Revises: 
Create Date: 2026-07-20 05:26:30.732859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddf7328e83fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ── 1. Create PostgreSQL custom enum types first ───────────────────────────
    # These must exist before the tables that reference them.
    op.execute("""
        CREATE TYPE user_role AS ENUM (
            'staff', 'director', 'backup_director', 'regional_admin',
            'compliance_reviewer', 'operations_support'
        )
    """)
    op.execute("""
        CREATE TYPE incident_status AS ENUM (
            'draft', 'submitted', 'changes_requested', 'under_review',
            'approved', 'guardian_ack_pending', 'acknowledged',
            'ack_unreachable', 'closed', 'restricted_review'
        )
    """)
    op.execute("""
        CREATE TYPE severity_level AS ENUM (
            'low', 'moderate', 'high', 'critical'
        )
    """)

    # Use postgresql.ENUM with create_type=False — types are already created above.
    # sa.Enum still fires _on_table_create even with create_type=False in some SA versions;
    # postgresql.ENUM(create_type=False) is the reliable way to reference existing types.
    user_role = postgresql.ENUM(
        'staff', 'director', 'backup_director', 'regional_admin',
        'compliance_reviewer', 'operations_support',
        name='user_role', create_type=False,
    )
    incident_status = postgresql.ENUM(
        'draft', 'submitted', 'changes_requested', 'under_review',
        'approved', 'guardian_ack_pending', 'acknowledged',
        'ack_unreachable', 'closed', 'restricted_review',
        name='incident_status', create_type=False,
    )
    severity_level = postgresql.ENUM(
        'low', 'moderate', 'high', 'critical',
        name='severity_level', create_type=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('is_demo_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_active_mobile_installations', sa.Integer(), nullable=False),
    sa.Column('synthetic_marker', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('category_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('photo_permitted', sa.Boolean(), nullable=False),
    sa.Column('ai_assistance_permitted', sa.Boolean(), nullable=False),
    sa.Column('structured_observation_required', sa.Boolean(), nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('center_id', 'category', name='uq_category_responses_center_cat')
    )
    op.create_table('children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('classroom', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('synthetic_marker', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('synthetic_marker', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'claimed', 'processed', 'failed')", name='ck_outbox_events_status'),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('external_subject', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', user_role, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('synthetic_marker', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_subject')
    )
    op.create_table('child_guardians',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ),
    sa.PrimaryKeyConstraint('child_id', 'guardian_id')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('registered_user_id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('device_label', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("platform IN ('ios', 'ipados')", name='ck_devices_platform'),
    sa.CheckConstraint("status IN ('active', 'revoked', 'blocked')", name='ck_devices_status'),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['registered_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('status', incident_status, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('staff_selected_severity', severity_level, nullable=False),
    sa.Column('current_severity', severity_level, nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_time_precision', sa.String(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('original_factual_notes', sa.Text(), nullable=False),
    sa.Column('actions_taken', sa.Text(), nullable=False),
    sa.Column('treatment_response', sa.Text(), nullable=True),
    sa.Column('witnesses_known', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('notification_decision', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_director_id', sa.UUID(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("event_time_precision IN ('exact', 'estimated')", name='ck_incidents_event_time_precision'),
    sa.ForeignKeyConstraint(['assigned_director_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistant_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_id', sa.String(), nullable=False),
    sa.Column('suggestion_type', sa.String(), nullable=False),
    sa.Column('disposition', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('field_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("disposition IN ('accepted', 'rejected', 'edited')", name='ck_assistant_interactions_disposition'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attempted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('storage_object_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('capture_user_id', sa.UUID(), nullable=False),
    sa.Column('capture_device_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('other_child_possible', sa.Boolean(), nullable=False),
    sa.Column('upload_status', sa.String(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("media_type IN ('image/jpeg', 'image/heic')", name='ck_evidence_media_type'),
    sa.CheckConstraint("upload_status IN ('pending', 'uploading', 'ready', 'failed', 'unavailable')", name='ck_evidence_upload_status'),
    sa.CheckConstraint('byte_size <= 10485760', name='ck_evidence_byte_size'),
    sa.ForeignKeyConstraint(['capture_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['capture_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_object_uri')
    )
    op.create_table('incident_children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('involvement_role', sa.String(), nullable=False),
    sa.Column('child_specific_details', sa.Text(), nullable=True),
    sa.CheckConstraint("involvement_role IN ('primary_affected', 'involved', 'witness')", name='ck_incident_children_involvement_role'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'child_id', name='uq_incident_children')
    )
    op.create_table('legal_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('applied_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_kind', sa.String(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('original_staff_notes', sa.Text(), nullable=False),
    sa.Column('rendered_narrative', sa.Text(), nullable=False),
    sa.Column('structured_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('edit_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("version_kind IN ('staff_submission', 'director_edit', 'approved', 'addendum')", name='ck_report_versions_kind'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['report_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'version_number', name='uq_report_versions_incident_num')
    )
    op.create_table('retention_disposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=False),
    sa.Column('eligible_for_disposal', sa.Boolean(), nullable=False),
    sa.Column('blocked_by_legal_hold', sa.Boolean(), nullable=False),
    sa.Column('disposal_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'idempotency_key', name='uq_sync_ops_device_key')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('report_version_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['report_version_id'], ['report_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardian_packets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('approved_version_id', sa.UUID(), nullable=False),
    sa.Column('primary_guardian_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notification_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'sent', 'opened', 'acknowledged', 'disagreed', 'unreachable', 'closed')", name='ck_guardian_packets_status'),
    sa.ForeignKeyConstraint(['approved_version_id'], ['report_versions.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['primary_guardian_id'], ['guardians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'child_id', 'approved_version_id', name='uq_guardian_packets_incident_child_version')
    )
    op.create_table('report_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('viewer_user_id', sa.UUID(), nullable=False),
    sa.Column('report_version_id', sa.UUID(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['report_version_id'], ['report_versions.id'], ),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('report_version_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['report_version_id'], ['report_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acknowledgements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guardian_packet_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('typed_full_name', sa.String(), nullable=True),
    sa.Column('receipt_confirmed', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('disagreement_comment', sa.Text(), nullable=True),
    sa.Column('report_version_id', sa.UUID(), nullable=False),
    sa.Column('staff_present_user_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('in_person', 'email_link')", name='ck_acknowledgements_method'),
    sa.CheckConstraint("outcome IN ('acknowledged', 'disagreed')", name='ck_acknowledgements_outcome'),
    sa.ForeignKeyConstraint(['guardian_packet_id'], ['guardian_packets.id'], ),
    sa.ForeignKeyConstraint(['report_version_id'], ['report_versions.id'], ),
    sa.ForeignKeyConstraint(['staff_present_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_link_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('guardian_packet_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'used', 'expired', 'invalidated')", name='ck_email_link_tokens_status'),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['guardian_packet_id'], ['guardian_packets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('notification_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('guardian_packet_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('outbox_event_id', sa.UUID(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['guardian_packet_id'], ['guardian_packets.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # ── 2. Immutable-row triggers ─────────────────────────────────────────────
    # Prevent UPDATE and DELETE on append-only tables.
    op.execute("""
        CREATE OR REPLACE FUNCTION enforce_immutable_row()
        RETURNS TRIGGER LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'Rows in table % are immutable and cannot be updated or deleted.',
                TG_TABLE_NAME
                USING ERRCODE = 'restrict_violation';
        END;
        $$;
    """)
    for table in ('report_versions', 'acknowledgements', 'contact_attempts', 'audit_events'):
        op.execute(f"""
            CREATE TRIGGER trg_{table}_immutable
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION enforce_immutable_row();
        """)

    # ── 3. Required indexes (from db-schema.md) ───────────────────────────────
    op.create_index(
        'idx_incidents_queue',
        'incidents',
        ['center_id', 'status', 'current_severity', 'submitted_at'],
    )
    op.create_index(
        'idx_audit_incident_time',
        'audit_events',
        ['incident_id', 'occurred_at'],
    )
    op.create_index(
        'idx_contact_attempts',
        'contact_attempts',
        ['incident_id', 'attempted_at'],
    )



def downgrade() -> None:
    """Downgrade schema."""

    # ── Remove indexes ────────────────────────────────────────────────────────
    op.drop_index('idx_contact_attempts', table_name='contact_attempts')
    op.drop_index('idx_audit_incident_time', table_name='audit_events')
    op.drop_index('idx_incidents_queue', table_name='incidents')

    # ── Remove immutable triggers ─────────────────────────────────────────────
    for table in ('report_versions', 'acknowledgements', 'contact_attempts', 'audit_events'):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_immutable ON {table};")
    op.execute("DROP FUNCTION IF EXISTS enforce_immutable_row();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_deliveries')
    op.drop_table('email_link_tokens')
    op.drop_table('acknowledgements')
    op.drop_table('review_actions')
    op.drop_table('report_views')
    op.drop_table('guardian_packets')
    op.drop_table('audit_events')
    op.drop_table('sync_operations')
    op.drop_table('retention_disposals')
    op.drop_table('report_versions')
    op.drop_table('legal_holds')
    op.drop_table('incident_children')
    op.drop_table('evidence_items')
    op.drop_table('contact_attempts')
    op.drop_table('assistant_interactions')
    op.drop_table('incidents')
    op.drop_table('devices')
    op.drop_table('child_guardians')
    op.drop_table('users')
    op.drop_table('outbox_events')
    op.drop_table('guardians')
    op.drop_table('children')
    op.drop_table('category_responses')
    op.drop_table('centers')
    # ### end Alembic commands ###

    # ── Drop enum types ───────────────────────────────────────────────────────
    op.execute("DROP TYPE IF EXISTS severity_level;")
    op.execute("DROP TYPE IF EXISTS incident_status;")
    op.execute("DROP TYPE IF EXISTS user_role;")
